# Uncomment the next line to define a global platform for your project
#platform :ios, '12.0'

target 'APIExample' do
  use_frameworks!
  
  pod 'Floaty'
  pod 'AGEVideoLayout'
  pod 'AgoraRtcEngine_iOS'
  pod 'AgoraMediaPlayer_iOS'
end

target 'Agora-ScreenShare-Extension' do
  use_frameworks!
  
  pod 'AgoraRtcEngine_iOS'
end
